services:
  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db-pg
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/ewm-stats:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=statistics
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  user-service-db:
    image: postgres:16.1
    container_name: user-service-db-pg
    ports:
      - "6433:5432"
    volumes:
      - ./volumes/postgres/user-service:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=user
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  event-service-db:
    image: postgres:16.1
    container_name: event-service-db-pg
    ports:
      - "6434:5432"
    volumes:
      - ./volumes/postgres/event-service:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=event
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  request-service-db:
    image: postgres:16.1
    container_name: request-service-db-pg
    ports:
      - "6435:5432"
    volumes:
      - ./volumes/postgres/request-service:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=request
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  comment-service-db:
    image: postgres:16.1
    container_name: comment-service-db-pg
    ports:
      - "6436:5432"
    volumes:
      - ./volumes/postgres/comment-service:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=comment
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  category-service-db:
    image: postgres:16.1
    container_name: category-service-db-pg
    ports:
      - "6437:5432"
    volumes:
      - ./volumes/postgres/category-service:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=category
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

#  discovery-server:
#    build: ./infra/discovery-server
#    container_name: discovery-server
#    ports:
#      - "8761:8761"
#
#  config-server:
#    build: ./infra/config-server
#    container_name: config-server
#    depends_on:
#      - discovery-server
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#
#  gateway-server:
#    build: ./infra/gateway-server
#    container_name: gateway-server
#    ports:
#      - "8080:8080"
#    depends_on:
#      - discovery-server
#      - config-server
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#
#  user-service:
#    build: ./core/user-service
#    depends_on:
#      - discovery-server
#      - config-server
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-service-db:5432/user
#      - SPRING_DATASOURCE_USERNAME=main
#      - SPRING_DATASOURCE_PASSWORD=main
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#
#  event-service:
#    build: ./core/event-service
#    depends_on:
#      - discovery-server
#      - config-server
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-service-db:5432/event
#      - SPRING_DATASOURCE_USERNAME=main
#      - SPRING_DATASOURCE_PASSWORD=main
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#
#  request-service:
#    build: ./core/request-service
#    depends_on:
#      - discovery-server
#      - config-server
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://request-service-db:5432/request
#      - SPRING_DATASOURCE_USERNAME=main
#      - SPRING_DATASOURCE_PASSWORD=main
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#
#  comment-service:
#    build: ./core/comment-service
#    depends_on:
#      - discovery-server
#      - config-server
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://comment-service-db:5432/comment
#      - SPRING_DATASOURCE_USERNAME=main
#      - SPRING_DATASOURCE_PASSWORD=main
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#
#  category-service:
#    build: ./core/category-service
#    depends_on:
#      - discovery-server
#      - config-server
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://category-service-db:5432/category
#      - SPRING_DATASOURCE_USERNAME=main
#      - SPRING_DATASOURCE_PASSWORD=main
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#
#  stats-server:
#    build: ./stats/stats-server
#    depends_on:
#      - discovery-server
#      - config-server
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics
#      - SPRING_DATASOURCE_USERNAME=stat
#      - SPRING_DATASOURCE_PASSWORD=stat
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/