services:
  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db-pg
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/ewm-stats:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=statistics
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-db-pg
    ports:
      - "6432:5432"
    volumes:
      - ./volumes/postgres/ewm-main:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  discovery-server:
    build: ./infra/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"

  config-server:
    build: ./infra/config-server
    container_name: config-server
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  gateway-server:
    build: ./infra/gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/


  main-service:
    build: ./core/main-service
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  stats-server:
    build: ./stats/stats-server
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/